version: "3.9"

services:
  proxy:
    container_name: pm-proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./db:/app:cached
      - ./db/data:/var/lib/postgresql/data:cached
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_pm
    ports:
      - "5432:5432"

  # mysql:
  #   container_name: mysql
  #   image: mysql:5.7
  #   environment:
  #     DATABASE_URL: mysql://root:password@localhost:3306/dev
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - backend

volumes:
  data:
    driver: local
